######################################################################
# Automatically generated by qmake (2.01a) Tue Jan 29 20:03:24 2013
######################################################################

TEMPLATE = app
TARGET = imWatchingU 
DEPENDPATH += . Display Modules Display/NCurses Display/QT
INCLUDEPATH += . Modules Display Display/NCurses Display/QT
LIBS += -lncurses

# Input
HEADERS += ModuleCoreNCurses.h \
           AModuleCore.h \
           ModuleCoreQT.h \
           Utils.h \
           config.h \
           Display/AMonitorDisplay.h \
           Display/DisplayFactory.hpp \
           Display/IMonitorDisplay.h \
           Modules/AMonitorModule.h \
           Modules/IMonitorModule.h \
           Modules/ModuleCPU.h \
           Modules/ModuleDate.h \
           Modules/ModuleKernelVersion.h \
           Modules/ModuleMachineName.h \
           Modules/ModuleNetwork.h \
           Modules/ModuleRAM.h \
           Display/NCurses/NCursesBarre.h \
           Display/NCurses/NCursesDisplay.h \
           Display/NCurses/NCursesGraph.h \
           Display/NCurses/NCursesText.h \
           Display/QT/ModuleCoreQT.h \
           Display/QT/QTBarre.h \
           Display/QT/QTGraph.h \
           Display/QT/QTText.h
SOURCES += main.cpp \
           AModuleCore.cpp \
           ModuleCoreNCurses.cpp \
           Utils.cpp \
           Config.cpp\
           Display/AMonitorDisplay.cpp \
           Modules/AMonitorModule.cpp \
           Modules/ModuleCPU.cpp \
           Modules/ModuleDate.cpp \
           Modules/ModuleKernelVersion.cpp \
           Modules/ModuleMachineName.cpp \
           Modules/ModuleNetwork.cpp \
           Modules/ModuleRAM.cpp \
           Display/NCurses/NCursesDisplay.cpp \
           Display/NCurses/NCursesText.cpp \
           Display/NCurses/NCursesBarre.cpp \
           Display/QT/ModuleCoreQT.cpp \
           Display/QT/QTBarre.cpp \
           Display/QT/QTGraph.cpp \
           Display/QT/QTText.cpp
